### PR TITLE
Bo5280 add parser server

### PR DESCRIPTION
**Pull request by truongthanh96**
resolve https://github.com/QuodAI/front-office/issues/2354
Thanks @HuyQLuong

### CODE REVIEW

**Comment by truongthanh96** [comment]
Hi @HuyQLuong I am having trouble bundle webpack and run the file website/src/server.js . Do you have time to take a look and help me with this tomorrow?

**Comment by truongthanh96** [comment]
Ping Ping @HuyQLuong

**Comment by truongthanh96** [comment]
Hi @HuyQLuong , to summarize.
* Run website/src/server.js as a nodejs express server
* Build with only `src/parsers` and `src/server.js` to optimize build speed and size

Could you have a check, thanks

**Comment by HuyQLuong** [comment]
Yes, I will check it

**Comment by truongthanh96** [comment]
Thank you @HuyQLuong

**Comment by truongthanh96** [comment]
hi @HuyQLuong what I want to build is website folder on this PR. Not server. Could you have a check?
basically the file src/server.js and src/parsers/

**Comment by truongthanh96** [comment]
Done, image can be accessed at 326348232034.dkr.ecr.ap-southeast-1.amazonaws.com/de/ae_server:bo5280_add_parser_server.61a0d6

**Pull request merged**
